name = "blog-s2n-tech"
compatibility_date = "2025-07-21"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "./dist/_worker.js"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

[[kv_namespaces]]
binding = "CACHE"
id = "ca520efaf4c54033baf6af0408597068"
