name = "blog-s2n-tech"
compatibility_date = "2025-12-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "./dist/_worker.js"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

[images]
binding = "IMAGE"
