name = "blog-s2n-tech"
compatibility_date = "2025-12-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "./dist/_worker.js"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[images]
binding = "IMAGE"

[[kv_namespaces]]
binding = "CACHE"
id = "ca520efaf4c54033baf6af0408597068"
